name: Deploy react app to netlify using github actions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve the latest main branch
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install depenencies
        run: npm ci

      - name: Build the code found in the branch
        run: npm run build

      - name: Deploy to netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./distaaaaa
          production-deploy: true
          deploy-message: "Deployed from Github Actions"
          github-token: ${{ secrets.GITHUB_TOKEN}}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
